Beaver-Notes/Beaver-Notes

packages/renderer/src/pages/settings/Index.vue
packages/renderer/src/pages/settings/locales/zh.json

I made a Simplified Chinese translation based on English translation. I noticed that some translations were not applied to the program. And I'm not sure if the translation of some features is accurate.

feat(zh.json): Add Simplified Chinese translation.

---

packages/renderer/src/utils/commands.js
packages/renderer/src/utils/locales/zh.json

feat(zh.json): Add Simplified Chinese translation for command.

---

packages/renderer/src/pages/settings/Index.vue

Reverts Daniele-rolli/Beaver-Notes#45

🐞 Revert "fix(pages/Index.vue): fix can't select file in dialog"

---

packages/renderer/src/pages/settings/locales/de.json

Hi @Daniele-rolli,
I have added the new lines in the german translation.
Greetings
Danny

added new lines in german translation

---

packages/renderer/src/pages/settings/locales/zh.json

Add translation for remainder.

feat(locales/zh.json): add zh translation for sync reminder

---

packages/main/src/index.js
packages/renderer/src/App.vue
packages/renderer/src/pages/note/_id.vue
packages/renderer/src/pages/settings/Index.vue
packages/renderer/src/pages/settings/locales/zh.json

1. Fix the issue where placeholders are not displayed.
2. Fix the problem that zoom factor will be lost in some situation.
3. Add new translations.

Add translation and fix some problem

---

packages/main/src/index.js
packages/renderer/src/lib/tiptap/exts/image.js
packages/renderer/src/utils/copy-image.js

feat: support paste image from screenshot software

---

packages/renderer/src/pages/note/_id.vue

perf: auto focus the editor after typing enter

---

package.json
packages/renderer/src/pages/settings/locales/zh.json
scripts/transDiff.js

I also added a simple script to compare the differences with English.

Add new translations

---

packages/renderer/src/pages/settings/locales/nl.json

i think this is all the translation updates for 2.7.0

improved dutch language support for v. 2.7.0

---

packages/renderer/src/pages/settings/locales/de.json

Hello Daniele,
I have added your new lines (Issue #109) to the German translation.
Best regards
Danny

added new lines in german translation issue #109

---

packages/renderer/src/pages/settings/Index.vue
packages/renderer/src/pages/settings/locales/de.json

Index.vue double enty nl translation / de.json translation updated #116

---

packages/renderer/index.html
packages/renderer/src/assets/css/editor.css
packages/renderer/src/composable/editorImage.js
packages/renderer/src/utils/copy-image.js

1. fix the asset's path not found.
2. fix the remote picture link broken.
3. fix the picture offset in container.

fix: fix some bugs

---

packages/renderer/src/lib/tiptap/exts/Callouts/Black.js
packages/renderer/src/lib/tiptap/exts/Callouts/Blue.js
packages/renderer/src/lib/tiptap/exts/Callouts/Green.js
packages/renderer/src/lib/tiptap/exts/Callouts/Purple.js
packages/renderer/src/lib/tiptap/exts/Callouts/Red.js
packages/renderer/src/lib/tiptap/exts/Callouts/Yellow.js

Appending a space to `>[color]` will also take effect.

perf(callouts): enhance the callouts experience

---

packages/main/src/index.js
packages/preload/src/index.js
packages/renderer/src/App.vue
packages/renderer/src/components/app/AppSidebar.vue
packages/renderer/src/components/ui/Checkbox.vue
packages/renderer/src/pages/settings/Index.vue
packages/renderer/src/pages/settings/locales/de.json
packages/renderer/src/pages/settings/locales/en.json
packages/renderer/src/pages/settings/locales/it.json
packages/renderer/src/pages/settings/locales/nl.json
packages/renderer/src/pages/settings/locales/zh.json

1. Add notification for import and export.
2. Add setting toggle menu bar visibility.

add notification for import and export && add setting toggle menu bar visibility

---

packages/renderer/dist/index.html
packages/renderer/src/pages/settings/Index.vue

1. fix `ring` for `interface direction`.
2. fix image break after build due to dynamic string `src` for `img`.

fix: fix image issues

---

packages/main/src/index.js
packages/preload/src/index.js
packages/renderer/src/components/app/AppSidebar.vue
packages/renderer/src/composable/onClose.js

Reverts Beaver-Notes/Beaver-Notes#179

Revert "fix: remove the leaving process after quit"

---

packages/main/src/index.js
packages/main/src/server.js
packages/main/src/store/modules/settings.store.js
packages/main/src/token/index.js
packages/main/src/token/middleware.js
packages/preload/src/index.js
packages/renderer/src/App.vue

Test Steps:
1. Request token by `curl`. The confirm dialog will pop up in the editor.
2. Confirm it will create the token. The token will be displayed in the terminal.
3. Request `/confirm-auth` with the token. If it echos `passed`, it means the verification is passed.
There are commands:
Request for token.
```shell
curl --location 'http://localhost:3000/request-auth' \
--header 'Content-Type: application/json' \
--data '{
"platform": "postman",
"id": "4061716c-7cfd-4de2-acfd-d2c5376119cb"
}'
```
Request `/confirm-auth`. Replace `your-token` with the token you get.
```shell
curl --location --request GET 'http://localhost:3000/confirm-auth' \
--header 'Authorization: Bearer your-token' \
--header 'Content-Type: application/json' \
--data '{
"platform": "postman",
"id": …
```

Add authorization system

---

package.json
packages/renderer/src/components/note/NoteMenu.vue
packages/renderer/src/lib/tiptap/exts/drawing-block/Component.vue
packages/renderer/src/lib/tiptap/exts/drawing-block/index.js
packages/renderer/src/pages/settings/Index.vue
packages/renderer/src/pages/settings/locales/en.json
packages/renderer/src/utils/markdown.js

- Fixed tables
- Added markdown import & export notifications

Fixes for version 3.7.0

---

packages/renderer/src/lib/tiptap/exts/collapse-heading/index.js
packages/renderer/src/lib/tiptap/exts/footnote-block/utils.ts
packages/renderer/src/store/note.js

Fix content lost after the title expands, while ensuring that it will exist as well after turning off the collapsible heading.
https://github.com/orgs/Beaver-Notes/discussions/252#discussioncomment-12639530
None.
https://github.com/user-attachments/assets/e9df8d4c-4713-45ea-9cf5-483913cdb6e9

fix: fix content lost after heading expansion

---

electron-builder.config.cjs
packages/main/src/index.js
packages/renderer/src/lib/tiptap/exts/audio-block/AudioComponent.vue
packages/renderer/src/lib/tiptap/exts/video-block/VideoComponent.vue
yarn.lock

fix: media loading cripples performance

4.0.0 - media loading
